-- ==========================================================================
-- Esquema do FakeERP (H2). Idempotente para preservar os dados em disco.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS tbl_users (
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50)  NOT NULL DEFAULT 'ROLE_USER'
);

CREATE TABLE IF NOT EXISTS tbl_orders (
    order_id        BIGINT PRIMARY KEY,
    order_date_time TIMESTAMP      NOT NULL,
    value           DECIMAL(15, 2) NOT NULL,
    discount        DECIMAL(15, 2) NOT NULL,
    total           DECIMAL(15, 2) NOT NULL,
    status          VARCHAR(50)    NOT NULL
);

-- ==========================================================================
-- Escopos JWT por usuário (separados por espaço, ex.: "report:read policy:read")
-- ==========================================================================
ALTER TABLE tbl_users ADD COLUMN IF NOT EXISTS scopes VARCHAR(255) DEFAULT '' NOT NULL;

-- ==========================================================================
-- Squad de crédito PJ
-- ==========================================================================

-- Cadastro das empresas (consultado pelo Agente Analista)
CREATE TABLE IF NOT EXISTS tbl_company (
    cnpj                     CHAR(14)       PRIMARY KEY,
    corporate_name           VARCHAR(200)   NOT NULL,
    trade_name               VARCHAR(200),
    segment                  VARCHAR(50)    NOT NULL,
    founded_at               DATE           NOT NULL,
    declared_monthly_revenue DECIMAL(15, 2) NOT NULL
);

-- Política de crédito versionada (consultada pelo Agente Compliance)
CREATE TABLE IF NOT EXISTS tbl_credit_policy (
    id                              BIGINT AUTO_INCREMENT PRIMARY KEY,
    policy_version                  VARCHAR(20)    NOT NULL,
    segment                         VARCHAR(50)    NOT NULL,
    min_months_active               INT            NOT NULL,
    min_monthly_revenue             DECIMAL(15, 2) NOT NULL,
    max_discount_rate_allowed       DECIMAL(5, 4)  NOT NULL,
    min_orders_count_last_3_months  INT            NOT NULL,
    max_requested_amount            DECIMAL(15, 2) NOT NULL,
    updated_at                      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_credit_policy_version_segment UNIQUE (policy_version, segment)
);

-- Decisões de crédito (gravadas pelo Agente Coordenador, aprovadas por humano).
-- Sem DELETE: correções viram nova revisão (supersedes_id), nunca apagam a anterior.
-- A constraint única impede que um agente reprocessando a mesma proposta
-- grave a decisão em duplicidade.
CREATE TABLE IF NOT EXISTS tbl_credit_decision (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    cnpj                CHAR(14)       NOT NULL,
    reference_year      INT            NOT NULL,
    reference_month     INT            NOT NULL,
    revision            INT            DEFAULT 0 NOT NULL,
    requested_amount    DECIMAL(15, 2) NOT NULL,
    proposed_score      DECIMAL(4, 3)  NOT NULL,
    decision            VARCHAR(20)    NOT NULL,
    status              VARCHAR(20)    NOT NULL,
    policy_version      VARCHAR(20)    NOT NULL,
    analyst_agent_id    VARCHAR(100)   NOT NULL,
    compliance_agent_id VARCHAR(100)   NOT NULL,
    justification       VARCHAR(4000)  NOT NULL,
    supersedes_id       BIGINT,
    created_by          VARCHAR(100)   NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    approved_by         VARCHAR(100),
    approved_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_credit_decision_company    FOREIGN KEY (cnpj) REFERENCES tbl_company (cnpj),
    CONSTRAINT fk_credit_decision_supersedes FOREIGN KEY (supersedes_id) REFERENCES tbl_credit_decision (id),
    CONSTRAINT uq_credit_decision_period     UNIQUE (cnpj, reference_year, reference_month, revision)
);
